### ISSUE TITLE
Eliminar comentarios

### ISSUE THREAD

**Issue by NicoGonzalez94** [mdiazlinares/backend_tp3#16]
Buenas! como va? encontre algunos comentarios en el codigo,

![image](https://github.com/user-attachments/assets/ae3b3228-cb73-407f-b3d5-c9a96ae80ea3)

Recuerden, los comentarios no estan vistos como una buena practica , pero en si el codigo comentado es mucho menos aceptado.

Cualquier cosita podes contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by mdiazlinares** [comment]
Buenas tardes profe, ya se eliminaron los comentarios.
